server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: WeDbTD243n
    url: jdbc:postgresql://localhost:5433/selekcijskiZad
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true